Repository dnd-side-project/dnd-6th-4-ping-pong, pull requests merged in 2022-01, with the labels that each got.

#2 새로운 프로젝트 생성
  .gitignore
  .idea/.gitignore
  .idea/checkstyle-idea.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/dnd/sixth/lmsservice/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/sixth/lmsservice/App.kt
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/RepositoryModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/base/BaseActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/base/BaseViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/MainActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/MainViewModel.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/dnd/sixth/lmsservice/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Priority: Medium, Status: Review Needed

#5 Merge develop branch with master branch
  .gitignore
  .idea/.gitignore
  .idea/checkstyle-idea.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/dnd/sixth/lmsservice/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/sixth/lmsservice/App.kt
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/RepositoryModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/base/BaseActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/base/BaseViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/MainActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/MainViewModel.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/dnd/sixth/lmsservice/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Priority: Low, Status: In Progress, Type: Feature

#15 Design(home): "Make layout of home activity"
  .idea/.name
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/home/HomeActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/home/HomeViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/MainActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/MainViewModel.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/img_temp.png
  app/src/main/res/font/fonts.xml
  app/src/main/res/font/roboto_regular.ttf
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_class.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/values/views.xml
Labels: Priority: Medium, Status: Review Needed

#24 Design(invite dialog): "Create layout of invite dialog"
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/making/InviteDialogFragment.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/making/MakeClassActivity.kt
  app/src/main/res/drawable/bg_invite_code.xml
  app/src/main/res/drawable/bg_round_dialog.xml
  app/src/main/res/drawable/selector_copy_btn.xml
  app/src/main/res/layout/activity_make_class.xml
  app/src/main/res/layout/fragment_invite_dialog.xml
  app/src/main/res/values/strings.xml
Labels: Status: On Hold

#30 Design(calendar): "Design calendar activity layout"
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/sixth/lmsservice/App.kt
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/adapter/viewpager/MainViewPagerAdapter.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/LoginActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/CalendarFragment.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/CalendarViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/utility/ToolTipManager.kt
  app/src/main/res/drawable/bg_switch_thumb.xml
  app/src/main/res/drawable/bg_switch_track.xml
  app/src/main/res/drawable/btn_copy.xml
  app/src/main/res/drawable/btn_make_class_day.xml
  app/src/main/res/drawable/btn_salary_radio.xml
  app/src/main/res/drawable/ic_more.png
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_make_class.xml
  app/src/main/res/layout/fragment_invite_dialog.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/views.xml
Labels: Priority: Medium, Type: Feature, Type: Design

#32 Design(class) : Make ClassProgressFragment layout and viewmodel
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/lesson/progress/ClassProgressFragment.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/lesson/progress/ClassProgressViewModel.kt
  app/src/main/res/drawable/bg_round_white_btn.xml
  app/src/main/res/layout/fragment_class_progress.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Priority: Medium, Type: Design

#34 Feature(createPackage): create Package data and domain
  app/build.gradle
  app/src/main/java/com/dnd/sixth/lmsservice/data/network/ApiService.kt
  app/src/main/java/com/dnd/sixth/lmsservice/data/network/ProvideAPI.kt
  app/src/main/java/com/dnd/sixth/lmsservice/data/network/Url.kt
  app/src/main/java/com/dnd/sixth/lmsservice/data/preference/PreferenceManager.kt
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/RepositoryModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/domain/useCase/UseCase.kt
  app/src/main/res/layout/fragment_class_progress.xml
  build.gradle
Labels: Priority: High, Type: Feature

#36 Design(signUp) : make SignUpActivity and layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/signup/SignUpActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/signup/SignUpViewModel.kt
  app/src/main/res/drawable/ic_baseline_visibility_off_24.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/colors.xml
Labels: Priority: Medium, Type: Design

#54 Feature/53 communication home layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/adapter/viewpager/CommunicationPagerAdapter.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/CommunicationMainActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/CommunicationMainViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/home/CommunicationHomeFragment.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/home/CommunicationHomeViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/CommunicationFragment.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/CommunicationViewMoel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/notice/write/NoticeAnswerAcitivty.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/notice/write/NoticeAnswerViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/notice/write/NoticeWriteActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/notice/write/NoticeWriteViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/lesson/progress/ClassProgressFragment.kt
  app/src/main/res/drawable-v24/btn_week_schedule_check_box.xml
  app/src/main/res/drawable/bg_round_white_btn.xml
  app/src/main/res/layout/activity_communication_main.xml
  app/src/main/res/layout/activity_notice_answer.xml
  app/src/main/res/layout/activity_notice_write.xml
  app/src/main/res/layout/fragment_communication.xml
  app/src/main/res/layout/fragment_communication_home.xml
Labels: Priority: Medium, Type: Design

#57 Design(communication) : Delete layout and activity,fragment,adapter a…
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/adapter/viewpager/CommunicationPagerAdapter.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/CommunicationMainActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/CommunicationMainViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/home/CommunicationHomeFragment.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/home/CommunicationHomeViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/CommunicationFragment.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/CommunicationViewMoel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/notice/write/NoticeAnswerAcitivty.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/notice/write/NoticeAnswerViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/notice/write/NoticeWriteActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/communication/noticeAndProposal/notice/write/NoticeWriteViewModel.kt
  app/src/main/res/layout/activity_communication_main.xml
  app/src/main/res/layout/activity_notice_answer.xml
  app/src/main/res/layout/activity_notice_write.xml
  app/src/main/res/layout/fragment_communication.xml
  app/src/main/res/layout/fragment_communication_home.xml
Labels: Priority: Medium, Type: Design

#59 Design(feedback) : Make layout of FeedBackStart and FeedBackWrite
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/StartFeedBackActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/StartFeedBackViewModel.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/WriteFeedBackActivity.kt
  app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/WriteFeedBackViewModel.kt
  app/src/main/res/drawable/bg_checkbox_outline_blank.xml
  app/src/main/res/drawable/bg_round_white_line_btn.xml
  app/src/main/res/drawable/bg_switch_thumb_am_pm.xml
  app/src/main/res/drawable/bg_switch_track_am_pm.xml
  app/src/main/res/drawable/ic_arrow_back_btn.xml
  app/src/main/res/drawable/ic_baseline_access_time_24.xml
  app/src/main/res/drawable/ic_baseline_date_range.xml
  app/src/main/res/layout/activity_start_feed_back.xml
  app/src/main/res/layout/activity_write_feed_back.xml
  app/src/main/res/values/switch_style.xml
Labels: Priority: Medium, Type: Design
